version: '3'

services:
    db:
        image: postgres
        container_name: db
        restart: unless-stopped
        ports:
            - '5432:5432'
        env_file:
            - config.env
        volumes:
            - database-data:/var/lib/postgresql/data/
        network_mode: host

volumes:
    database-data:
